version: '3.7'

services:
###
  postgres:
    image: postgres:latest
    container_name: 'postgresql'
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}

    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
###
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
###
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
