version: '3.7'

services:
###
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
###
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
